version: "3.8"
services:
  api:
    build: .
    container_name: aqi-fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Karachi
    volumes:
      - model_cache:/app/temp/production_models
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  model_cache:


