name: Hourly AQI Data Pipeline

on:
  workflow_dispatch:  # Manual trigger
  repository_dispatch:  # External API trigger
    types: [hourly-trigger]

jobs:
  hourly-update:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Add timeout
    permissions:
      contents: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create necessary directories
        run: |
          mkdir -p logs
          mkdir -p data

      - name: Run automated hourly update script
        run: |
          python automated_hourly_run.py
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          IQAIR_API_KEY: ${{ secrets.IQAIR_API_KEY }}

      - name: Upload logs and data on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: aqi-logs-${{ github.run_number }}
          path: |
            automated_run.log
            logs/
            data/
          retention-days: 7