name: Hourly AQI Data Pipeline

on:
  schedule:
    # Runs at the beginning of every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allows manual triggering from the GitHub UI

jobs:
  hourly-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # Cache dependencies

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create necessary directories
        run: |
          mkdir -p logs
          mkdir -p data

      - name: Download previous validation CSV (if exists)
        uses: actions/download-artifact@v4
        with:
          name: aqi-validation-csv
          path: data
        continue-on-error: true

      - name: Pull latest data from repo
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git pull origin main --allow-unrelated-histories --rebase

      - name: Run automated hourly update script
        # This script handles data collection, feature engineering,
        # and pushing to Hopsworks.
        run: |
          python automated_hourly_run.py
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          IQAIR_API_KEY: ${{ secrets.IQAIR_API_KEY }}

      - name: Upload updated validation CSV
        uses: actions/upload-artifact@v4
        with:
          name: aqi-validation-csv
          path: data/aqi_validation_current_*.csv

      - name: Commit and push AQI validation data files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/aqi_validation_current_*.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update AQI validation data - ${{ github.run_number }}"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main

      - name: Upload logs and data on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: aqi-logs-${{ github.run_number }}
          path: |
            automated_run.log
            logs/
            data/
          retention-days: 7 