name: Manual Historic AQI Data Backfill

on:
  workflow_dispatch:
    # Allows manual triggering from the GitHub UI for one-time backfill

jobs:
  historic-backfill:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # Cache dependencies

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create necessary directories
        run: |
          mkdir -p logs
          mkdir -p data

      - name: Run manual historic backfill script
        # This script handles historical data collection, feature engineering,
        # and pushing to Hopsworks for initial backfill.
        run: |
          python manual_historic_run.py
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          IQAIR_API_KEY: ${{ secrets.IQAIR_API_KEY }}

      - name: Commit and push AQI validation data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/aqi_validation_historic_*.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Add historic AQI validation data - ${{ github.run_number }}"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main

      - name: Upload logs and data on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: historic-backfill-logs-${{ github.run_number }}
          path: |
            manual_run.log
            logs/
            data/
          retention-days: 7 